# Generated by Django 4.0.3 on 2022-03-31 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('From', models.DateField()),
                ('To', models.DateField()),
                ('Reason', models.CharField(max_length=50)),
                ('Leave_type', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='PaidHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Holiday', models.CharField(max_length=50)),
                ('Date', models.DateField()),
            ],
        ),
    ]
