# Generated by Django 4.0.3 on 2022-03-31 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_employee_paidholiday'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employee',
            new_name='EmployeeLeave',
        ),
    ]
