# Generated by Django 4.0.3 on 2022-03-31 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_rename_employee_employeeleave'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paidholiday',
            old_name='Date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='paidholiday',
            old_name='Holiday',
            new_name='holiday',
        ),
    ]
