# Generated by Django 4.0.3 on 2022-03-31 15:23

from django.db import migrations, models
import leave_management_system.account.models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_rename_date_paidholiday_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeleave',
            name='From',
            field=models.DateField(validators=[leave_management_system.account.models.present_or_future_date]),
        ),
        migrations.AlterField(
            model_name='employeeleave',
            name='To',
            field=models.DateField(validators=[leave_management_system.account.models.present_or_future_date]),
        ),
    ]
