# Generated by Django 4.0.3 on 2022-03-31 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_employeeleave_from_alter_employeeleave_to'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeeleave',
            old_name='From',
            new_name='date_from',
        ),
        migrations.RenameField(
            model_name='employeeleave',
            old_name='To',
            new_name='date_to',
        ),
        migrations.RenameField(
            model_name='employeeleave',
            old_name='Reason',
            new_name='reason',
        ),
        migrations.RemoveField(
            model_name='employeeleave',
            name='Leave_type',
        ),
        migrations.AddField(
            model_name='employeeleave',
            name='leave_type',
            field=models.CharField(choices=[('c', 'casual leave'), ('p', 'paid leave')], default=None, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='leave',
            field=models.IntegerField(default=True, editable=False, null=True),
        ),
    ]
