# Generated by Django 4.0.3 on 2022-03-31 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_user_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='leave',
            field=models.IntegerField(default=2, editable=False, null=True),
        ),
    ]
