# Generated by Django 4.0.3 on 2022-03-31 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_user_leave'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='user',
        #     name='user_name',
        #     field=models.CharField(default=None, max_length=50),
        #     preserve_default=False,
        # ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
