# Generated by Django 4.0.3 on 2022-03-31 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_user_user_name_alter_user_first_name'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='user',
        #     name='user_name',
        # ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
    ]
