# Generated by Django 4.0.3 on 2022-03-31 16:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_employeeleave_is_approved_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeleave',
            name='user',
            field=models.ForeignKey(null=True,default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employeeleave',
            name='is_approved_key',
            field=models.BooleanField(default=True, editable=False, max_length=50),
        ),
    ]
