# Generated by Django 4.0.3 on 2022-04-01 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_alter_employeeleave_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeleave',
            name='is_approved_key',
            field=models.BooleanField(default=False, editable=False, max_length=50),
        ),
    ]
